name: Rust Build Dry Run

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: [ubuntu-latest, macos-13, macos-12, macos-11]
    steps:
    - uses: actions/checkout@v3
    - name: Debug Build
      run: cargo build --verbose
    - name: Release Build
      run: cargo build --verbose --release
